name: Deploy Backend to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure GCP
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push Image
        run: |
          gcloud builds submit ./backend \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
